### ISSUE TITLE
Metadaten einlesen / Maschinenlesbar machen

### ISSUE THREAD

**Issue by ubergesundheit** [codeformuenster/verkehrsunfaelle#11]
Die Datei [Legenden zur Unfallstatistik 2015 04. März 2016.pdf](https://github.com/codeformuenster/open-data/blob/master/Unfallstatistiken/Rohdaten/Legenden%20zur%20Unfallstatistik%202015%2004.%20M%C3%A4rz%202016.pdf) enthält Informationen zu Angaben im Datensatz

- Herausfinden welche Spalten beschrieben werden
- Daten aus dem PDF maschinenlesbar machen und in Kinto importieren

**Comment by thunfischtoast** [comment]
- [x] Unfallarten
- [x] Verkehrsbeteiligung
- [x] Unfallkategorien
- [x] Unfallursachen

**Comment by thunfischtoast** [comment]
https://github.com/codeformuenster/verkehrsunfaelle/tree/metadata_legend ist der Branch, auf dem gearbeitet wird

**Comment by silberzwiebel** [comment]
evtl. zusätzlich noch interessant: https://recht.nrw.de/lmi/owa/br_bes_text?anw_nr=1&bes_id=12186
(wir haben zu viele Issues für dieses Thema ...)
