### ISSUE TITLE
Inkonsistente Postgres-Rollen

### ISSUE THREAD

**Issue by thunfischtoast** [codeformuenster/verkehrsunfaelle#15]
In der Readme-Anleitung und docker-compose steht "accidents", in dem quay-Image wird aber 'postgres' verwendet.

**Comment by ubergesundheit** [comment]
Also ich glaube ich weiß was hier passiert:

Das Postgres image unterstüzt durch verschiedene environment Variablen (auf dem das quay-image basiert) z.B. den User oder den Namen der Datenbank zu bestimmen. Der Datenbank-Dump der beim erstmaligen Starten importiert wird, enthält weder Datenbankname noch Username. Beides wird durch das Initialisierungsskript (oder eben den User der den Container startet) bestimmt.

Jetzt kommt der Unterschied: Die docker-compose.yml bestimmt den usernamen, der Befehl in der Readme nicht. Deswegen hast du wahrscheinlich container mit unterschiedlichen Datenbanknamen.

Habe mal versucht das in commit 8b7c6d1 zu korrigieren. Bitte mal ausprobieren und dann gerne hier schliessen. :)

**Comment by ubergesundheit** [comment]
Hier die Erklärung zu den Environment Variablen: https://hub.docker.com/_/postgres#environment-variables
